client_configs:
  comm_configs:
    compressor_configs:
      enable_compression: false
      error_bound: 1
      error_bounding_model: REL
      lossless_compressor: blosc
      lossy_compressor: SZ2Compressor
      param_cutoff: 1024
  model_configs:
    model_kwargs:
      d_model: 128
      lookahead: 4
      lookback: 12
      s_size: 7
      u_size: 2
      x_size: 6
      y_size: 1
    model_name: Transformer
    model_path: /home/exx/shourya/time-series-forecasting-federation/models/TRANSFORMER/TransformerN.py
  train_configs:
    do_pre_validation: false
    do_validation: true
    loss_fn_name: MSELoss
    loss_fn_path: /home/exx/shourya/time-series-forecasting-federation/files_for_appfl/loss.py
    metric_name: mape
    metric_path: /home/exx/shourya/time-series-forecasting-federation/files_for_appfl/metric.py
    mode: step
    num_local_steps: 4
    optim: SGD
    optim_args:
      lr: 1.0e-05
    train_batch_size: 32
    train_data_shuffle: true
    trainer: NaiveTrainer
    val_batch_size: 32
    val_data_shuffle: false
server_configs:
  aggregator: FedAvgAggregator
  aggregator_kwargs:
    checkpoint_dirname: /home/exx/shourya/time-series-forecasting-federation/.logs/YTVlZ_transformern_HFLNoOverlap_nodereplace_0/server
    checkpoint_filename: model
    checkpoint_interval: 1
    client_weights_mode: equal
    do_checkpoint: false
    replace: true
    server_learning_rate: 1
  comm_configs:
    grpc_configs:
      max_message_size: 1048576
      server_uri: localhost:50051
      use_ssl: false
  device: cpu
  logging_output_dirname: /home/exx/shourya/time-series-forecasting-federation/.logs/YTVlZ_transformern_HFLNoOverlap_nodereplace_0/server
  logging_output_filename: result
  num_global_epochs: 50
  scheduler: SyncScheduler
  scheduler_kwargs:
    num_clients: 2
    same_init_model: true
