client_configs:
  comm_configs:
    compressor_configs:
      enable_compression: false
      error_bound: 0.001
      error_bounding_model: REL
      lossless_compressor: blosc
      lossy_compressor: SZ2Compressor
      param_cutoff: 1024
  model_configs:
    model_kwargs:
      lookahead: 4
      lookback: 12
      s_size: 7
      u_size: 2
      x_size: 6
      y_size: 1
    model_name: Transformer
    model_path: /home/sbose/time-series-forecasting-federation/models/TRANSFORMER/Transformer.py
  train_configs:
    do_pre_validation: true
    do_validation: true
    loss_fn_name: MSELoss
    loss_fn_path: /home/sbose/time-series-forecasting-federation/files_for_appfl/loss.py
    metric_name: mape
    metric_path: /home/sbose/time-series-forecasting-federation/files_for_appfl/metric.py
    mode: step
    num_local_steps: 1
    optim: Adam
    optim_args:
      lr: 0.001
    train_batch_size: 64
    train_data_shuffle: true
    trainer: NaiveTrainer
    val_batch_size: 64
    val_data_shuffle: true
server_configs:
  aggregator: FedAvgAggregator
  aggregator_kwargs:
    client_weights_mode: equal
    server_learning_rate: 0.01
  comm_configs:
    grpc_configs:
      max_message_size: 1048576
      server_uri: localhost:50051
      use_ssl: false
  device: cpu
  logging_output_dirname: /home/sbose/time-series-forecasting-federation/.logs/YTZlZTVmMz_transformer/server
  logging_output_filename: result
  num_global_epochs: 25
  scheduler: SyncScheduler
  scheduler_kwargs:
    num_clients: 12
    same_init_model: true
